### ISSUE TITLE
Error in coxph.wtest... NA/NaN/Inf in foreign function call

### ISSUE THREAD

**Issue by jgarces02** [therneau/survival#103]
Dear @therneau, 

How's it going? I've recently post a problem on [StackOverflow](https://stackoverflow.com/questions/60988494/boostraping-with-censored-data-error-resampling-data) but I guess that I don't understand correctly the issue... could you give me a clue, please? Thanks in advance!

--------

I paste below the entire post to facilitate things:

> 
> I'm performing a boostraped Cox regression (stepwise forward) with censored clinical data (i.e., event 0/1 and time to event). I'm having the following error...
> 
>     Error in coxph.wtest(fit$var[nabeta, nabeta], temp, control$toler.chol) : 
>       NA/NaN/Inf in foreign function call (arg 3)
> 
> .. I guess (based on this [other question](https://stats.stackexchange.com/questions/180196/survival-analysis-no-one-failed-during-the-period-of-the-study)) that's because in one (or several) bootstraping steps the resampling is randomly taking only values equal to 1 or to 0 so inner `coxph` transformation is creating `NA/NaN/Inf` values. I've used this code:
> 
> ```
> multicox.fwd.boot <- function(data, d){
>   aux_data <- data[d,]
>   
>   fit_null_pfs <- coxph(Surv(time, event) ~ 1, data = aux_data) 
>   fit_full_pfs <- coxph(Surv(time, event) ~ ., data = aux_data)
>   
>   fit_fw_pfs <- step(fit_null_pfs, direction = "forward", k = qchisq(0.05, 1, lower.tail = F),
>                      scope = list(lower = formula(fit_null_pfs), upper = formula(fit_full_pfs)))
>   cf <- coef(fit_fw_pfs)
>   
>   # bootstraping is failing because not all variables are being introduced in each step (bit.ly/2UwQCay)
>   df <- setdiff(colnames(aux_data), names(cf))[-c(1,2)] #to not consider event/time
>   ad <- rep(0, length(df))
>   names(ad) <- df
>   return(c(cf, ad))
> }
> 
> cb <- censboot(data = gexclin, R = 10, statistic = multicox.fwd.boot)
> ```
> Any idea to kept a "balanced" distribution of this 0/1 events? Or another approach more useful?
> 
> **EDIT**
> I've tested the distribution of events in each bootstrap's iteration and it seems the error could be another different one... so, I don't understand this problem :===(
> 
> ```
> multicox.fwd.boot <- function(...){
>     ...
>     cat(">>>Boot iteration,\n\t", table(aux_data$event), "\n")
>     ...
> }
> 
> >>>Boot iteration,
> 	 64 35 
> >>>Boot iteration,
> 	 62 37 
> >>>Boot iteration,
> 	 64 35 
> >>>Boot iteration,
> 	 57 42 
> >>>Boot iteration,
> 	 71 28 
> >>>Boot iteration,
> 	 63 36 
> Error in coxph.wtest(fit$var[nabeta, nabeta], temp, control$toler.chol) : 
>   NA/NaN/Inf in foreign function call (arg 3)
> ```

**Comment by therneau** [comment]
These errors are very hard to chase down without a reproducable example.   Usually, what has happened is that the Newton-Raphson iteration has gone off to a strange place such that exp() overflows, the estimated second derivative matrix has become singular, a negative variance due to accumulated round off error, or some such.   The routine tries to catch these, but new combinations of strangeness sometimes arise.  Take note for instance of the "fail" directory, which contains data sets that have been sent to me over time, each of which caused a failure like this, each of which allowed me to further harden the code against such things.    
The partial likelihood for a Cox model is a very well behaved function: it normally takes an exceptional data set and model to give it grief.  Questions like the above that show an error but give no concrete data are not helpful to me.

**Comment by therneau** [comment]
Closed
