### ISSUE TITLE
Error in summary.survfit() when times is too large

### ISSUE THREAD

**Issue by dwoll** [therneau/survival#111]
`summary.survfit()` results in an error if the model was fit to data where survival goes to 0, and the argument `times` is set to a value that is larger than the max survival time. Since I have not been able to reproduce the error using built-in datasets, I have created a gist with reproducible examples:

https://gist.github.com/dwoll/dda5f2b52af90d6de016744a915ca91a

Specifically, the error is generated in the last line of function `unlistsurv()` that is defined within `summary.survfit()` 

https://github.com/therneau/survival/blob/6cf5efeb4d68965d559f548a1ca593ef67fba553/R/survfitms.R#L341

However, the underlying source of the error might be in `print.survfit()` which generates warnings on line 57

https://github.com/therneau/survival/blob/fa53d8e7f9239906d3d49a37800ece52d9999830/R/print.survfit.R#L57

These two places are where some issues show up, but the underlying problem may well be somewhere else - unfortunately, my understanding of the underlying code is very limited.

Thank you for supporting the survival package! It has been absolutely essential to my daily work for several years now.

**Comment by therneau** [comment]
Two answers
First, the summary.survfit function has two purposes.  The original is to print out a curve for reading, and in that case a times argument past the end of the curve should print nothing.  The second is to pull off data for further used, in which case you want those values.   The extend argument deals with this, and you likely should be using extend=TRUE

Second, the code should not error out.  I've changed it so that you now will get a purposeful error message in this case, one that directs you to use the extend argument.
