### ISSUE TITLE
Survival curves of stratified coxph objects (is it a bug?)

### ISSUE THREAD

**Issue by drperpo** [therneau/survival#130]
In R survival vignette https://cran.r-project.org/web/packages/survival/vignettes/survival.pdf
on  page 45 a coxph object is defined as: 

**> cfit2 <- coxph(Surv(time, status) ~ age + sex + wt.loss + strata(inst), data=lung)**
On a new dataset 
**> dummy <- expand.grid(age=c(50, 60), sex=1, wt.loss=5)**
the predicted survival curves will have (as expected):
**> csurv2 <- survfit(cfit2, newdata=dummy)**
**> dim(csurv2)**
strata    data
      18     2

Now define 
**> dummy2 <- data.frame(age=c(50, 60), sex=1:2, wt.loss=5, inst=c(6,11))
> csurv3 <- survfit(cfit2, newdata=dummy2)
> dim(csurv3)**
strata
2
Say that I only want to define survival on just one case like so:

**dummy2 <- data.frame(age=60, sex=2, wt.loss=5, inst=11)
csurv3 <- survfit(cfit2, newdata=dummy2)
dim(csurv3)**
strata 
    18 
Then we are back to 18 strata, and 18 curves when plotting. 
Why would that be?

On another note, I thing the first example with dummy2 can be a bit confusing since the new data  has two strata and difference values for covars in each one. 

data.frame(age=c(50, 60), sex=1:2, wt.loss=5, inst=c(6,11))
  age sex wt.loss inst
1  50   1       5    6
2  60   2       5   11

**Comment by therneau** [comment]
When using inst=11, you should get one curve.  That's a bug.
When you get a set of 3 curves for a mix of data and strata, the result is a vector.  I probably should  figure out how to make dim return nothing but length return 3, to be consistent with other matrices and vectors (but I'm not sure how just yet).

**Comment by DRUgent** [comment]
I left a similar comment on [stackoverflow](https://stackoverflow.com/questions/67231786/survfit-for-stratified-cox-model) before encountering this thread.

Ideally, the calculations are made only for the strata in newdata - to save time and  memory with large datasets with lots of strata.

I believe I managed to find two places inside `survival:::coxsurv.fit` where the problem resides. Apologies if what follows next is completely wrong, the code is quite complex.

 1. The baselinehazards are calculated for every stratum instead of only those in the newdata (the loop is over all strata):
`
survival:::coxsurv.fit <- function (ctype, stype, se.fit, varmat, cluster, y, x, wt, risk, 
          position, strata, oldid, y2, x2, risk2, strata2, id2, unlist = TRUE) 
{
  
 ...

  if (is.factor(strata)) 
    ustrata <- levels(strata)
  else ustrata <- sort(unique(strata))

 ...

  for (i in 1:nstrata) {
    indx <- which(strata == ustrata[i])
    survlist[[i]] <- agsurv(y[indx, , drop = F], x[indx, 
                                                   , drop = F], wt[indx], risk[indx], survtype, vartype)
  }
...
`
 2. The second place, but here I'm much less sure, seems to be the following. If I understand correctly, the desired behavior (only outputting certain strata), only works if `id2` is not missing

`
coxsurv.fit <- function()

...

  if (missing(id2) || is.null(id2)) 
    result <- lapply(survlist, expand, x2, varmat, se.fit)
  else {
    onecurve <- function(slist, x2, y2, strata2, risk2, se.fit) {
...


`

**Comment by CSJCampbell** [comment]
[This patch](https://gist.github.com/CSJCampbell/09dfc0cee3365b3b38fccf0b108b209f) resolves the issue specifically mentioned, although there may be cases for which this doesn't cover. There are some tests to cover the cases considered. The patch removes the post-handling of the `coxsurv.fit` results which doesn't currently run and replaces it with trimming of the input data beforehand.

**Comment by therneau** [comment]
Things are more complicated than you might think.
The basic form for survival curves is to return a matrix-like object, dimensions of strata, data, states.    Simple curves are of course a vector of length 1.    This has become much more formal (and involved)  with the introduction of mult-state models.  Historically, there is one case where the strata/data portion was collapsed, but that is an anomaly.   The original note above showed that that exception does not always hold, due to some change I've made.   

Allowing an exception has lots of ripples downstream, for all the survfit methods.   I remember exactly why I allowed it, which was for coxph models with strata * covariate interactions, predicted curves for those have proven to be a real bear to get right.   One key starting question is why the test case that involve such interactions still works (frank.R).  My apologies that I haven't been able to get to this, but things have been a bit crazy.   I'll look at the patch with interest, but I can't directly accept it ---  the first line of the survfit.coxph.R function will tell you that the true source code is in the noweb directory.  Any fixes must be applied to the .Rnw files therein,  and those files strive for more comments than code.   Any test case needs significant comments as well.  (And yes, many of mine could use still more.)

**Comment by therneau** [comment]
This was forgotten for an embarrassingly long time,  I just got around to fixing it today.   The fix was essentially to correct an oversight: the code worried about the harder case of multiple curves with individually chosen strata and ignored the simple one of a single curve.
A complication in all this is that survival curves with multiple strata are not actually saved as a matrix, though they look like one.  The reason is that each stratum has a different number of points in the curve.   That dimension, the one where n can vary, is labeled "strata" by the dim() function, even for your case 2 which has 2 curves, where "data" would be a better label.
