### ISSUE TITLE
How is surv and cumhaz sorted in the object returned by survfit() with id?

### ISSUE THREAD

**Issue by flippercy** [therneau/survival#144]
Hi @therneau Dr Therneau:

I am wondering how surv and cumhaz are sorted in the objected returned by survfit() with id. I have codes as below:

data.dev.survival.fit= summary(survfit(coxph.model, newdata = data.dev.long, id=AccountID), times = 1:24)

data.dev.survival.probability = data.dev.survival.fit$surv

What I get from data.dev.survival.probability is a numeric vector containing the survival probability of each record (indexed by AccountID) from time 1 to 24. Could you tell me how these records are sorted, please? Are they sorted by the order of appearance in data.dev.long? Specifically, assume data.dev.long is like below:

AccountID TimeStart TimeEnd
11111        0               1
22222       0                1
00001      0                  1
11111        1               2
00001      1                   2
22222       1                2
......            ......              .....
........          ........            .......
...........       .........             .........

Then in data.dev.survival.probability, are the first 24 elements the survival probability of record 11111 from time 1 to 24, then record 22222 and 00001?

Thank you.

**Comment by therneau** [comment]
Because survival curves can be a different length for different strata, the result can't be a matrix with times= rows and cols= strata.  Instead the time/strata dimension is strung out: all the time points for strata 1, all the time points for strata 2, ...etc.    

But, overall, it is easier not to worry about this and use  dim(data.dev.survival.fit) to get the apparent dimensions, then use ordinary subscripts [ ] of the object to grab portions.  It is what I do myself to avoid confusion.  The dim.survfit and [.survfit methods have this all worked out.
