### ISSUE TITLE
royston function does not return nagelkerke's pseudo r2

### ISSUE THREAD

**Issue by barentroia** [therneau/survival#162]
Hi, 

according to the current documentation, the royston function returns a vector where R.n corresponds to the Nagelkerke's pseudo r2. From my understanding, when people refer to this pseudo r2, they refer to the pseudo r2 proposed by Nagelkerke in 1991, which rescales the Cox & Snell pseudo r2 by dividing it by 1-Likelihood(MIntercept)^2/N.

However, it seems that this rescaling step is not performed in the source code (see royston function, lines 80/81):
```
logtest <- -2 * (fit$loglik[1] - fit$loglik[2])
R.n = 1-exp(-logtest/fit$n)
```

I think that either the documentation should be modified to indicate that the Cox & Snell pseudo r2 is returned or the source code should be modified to include the rescaling step as follows:

`R.n = (1-exp(-logtest/fit$n))/(1-exp(fit$loglik[1])^(2/n)) 
`
or did I miss something?

**Comment by therneau** [comment]
The coxph routine added the Nagelkirke soon after it appeared, and reported it as a   "R-squared = xxxx   (max possible == yyy)", it never did the rescaling.    The decades since were not kind to the value and I eventually removed it from the default printout, but the line is still present in summary.coxph.R, unchanged for at least 20 years.

    rval$rsq<-c(rsq=1-exp(-logtest/cox$n),
                 maxrsq=1-exp(2*cox$loglik[1]/cox$n))


Reverse compatability with older code is always a debate, and I chose to use the long standing version from survival.    You make a good argument for change, however, and  I've updated the royston function.

**Comment by Feakster** [comment]
It might be useful to have both the Cox-Snell & Nagelkerke R<sup>2</sup> measures in the `royston()` function output. Riley's group have released an [R](https://cran.r-project.org/package=pmsampsize) & [Stata](https://ideas.repec.org/c/boc/bocode/s458569.html) package called [pmsampsize](https://doi.org/10.1002%2Fsim.7992) that uses the Cox-Snell R<sup>2</sup> or C statistic in order to calculate sample size requirements for deriving risk prediction models. Although the Nagelkerke R<sup>2</sup> measure is just a rescaled version of the Cox-Snell R<sup>2</sup>, having both readily available in the output will help less mathematically savvy users.
