### ISSUE TITLE
Problems with pseudo locating objects in the current environment/frame

### ISSUE THREAD

**Issue by Feakster** [therneau/survival#178]
I've been trying to write a function that calculates the observed risk using pseudovalues. To this end, I had written the following function:

```r
### observed() ###
observed <- function(object, ...) {

  ## Define S3 Method ##
  UseMethod('observed', object)

}


### observed.coxph() ###
observed.coxph <- function(object, newdata, times) {
  
  ## Checks ##
  if (is.null(object[['y']]))
    stop('Outcome data not embedded in model object.', call. = FALSE)
  
  ## Extraction ##
  if (missing(times)) times <- max(object[['y']][, 1])
  
  ## Extraction & Kaplan-Meier Estimator ##
  if (missing(newdata)) {
    
    # Extraction #
    S <- object[['y']]
    
    # Kaplan-Meier Estimator #
    fit_km <- survfit(
      formula = S ~ 1
    )
    
  } else {
    
    # Extraction #
    f <- formula(object) # Model formula.
    
    # Model Formula #
    f[3] <- 1 # KM formula.
    
    # Kaplan-Meier Estimator #
    fit_km <- survfit(
      formula = f,
      data = newdata,
      na.action = na.fail
    )
    
  }
  
  ## Pseudovalues ##
  obs <- 1 - pseudo(fit_km, times = times)[, 1]
  
  ## Output ##
  return(obs)
  
}
```

However, when implemented on an object of class `"coxph"`, (with the omission of the `newdata` parameter) the function was failing with the following error message:

```text
Error in eval(predvars, data, env) : object 'S' not found
```

This had me scratching my head for a while, as I initially thought the error was being triggered higher up by the `survfit()` function call, but it was actually being triggered by one of `pseudo()`'s nested function calls:

```r
traceback()
```
```text
11: eval(predvars, data, env)
10: eval(predvars, data, env)
9: model.frame.default(formula = S ~ 1)
8: stats::model.frame(formula = S ~ 1)
7: eval(expr, p)
6: eval(expr, p)
5: eval.parent(temp)
4: survresid.fit(fit, times = times, type = type, ...)
3: pseudo(fit_km, times = times) at calplot.R#98
2: observed.coxph(fit_cox) at calplot.R#51
1: observed(fit_cox)
```

All runs as intended if I use the superassignment bodge in the assignment of `S`, i.e.:

```r
# Extraction #
S <<- object[['y']]
on.exit(rm(S, envir = globalenv()))
```

A similar error is triggered when `newdata` is specified:

```text
Error in eval(x$call$formula) : object 'f' not found
```

```r
traceback()
```
```text
8: eval(x$call$formula)
7: eval(x$call$formula)
6: formula.default(object)
5: formula(object)
4: survresid.fit(fit, times = times, type = type, ...)
3: pseudo(fit_km, times = times) at calplot.R#98
2: observed.coxph(fit_cox, newdata = dat_test) at calplot.R#53
1: observed(fit_cox, newdata = dat_test)
```

**Comment by therneau** [comment]
You have fallen into the hall of mirrors formed by model.frame and formulas.   The original design flaw in S (Models in S, the "white book") was to make data= look for objects in the data frame instead of the usual parent, parent of parent, .... search path, instead making it use the data + the usual.   This led to lots of complaints.
 
R compounded this with formulas, which added layers of obscurity.   The upsphot is that it is almost impossible for follow up function to recreate data, when the original and follow up are inside a user function, i.e., call fit <- coxph, and then predict(fit, newdata) inside one of your  own functions.   It won't work.   I've spent hour and hours and finally gave up.

A work aound, but not a solution in my opinion, is to avoid any need to recreate by adding model=TRUE to the call.  It avoids the impassible tar pit.  The lm() and glm() functions threw in the towel and did this, but I work with some very large data sets and have been unwilling to keep reams of unneeded data copies just to avoid the occasional problem.    Your answer: add model=TRUE to the coxph call.

**Comment by Feakster** [comment]
Ah... that is indeed a bummer. I too have spent hours of life trying to work out what was going wrong. Unfortunately, setting `model = TRUE` isn't an option for me. I've been coding up some functions to give to a research group in a different country to externally validate our risk prediction models. Our information governance policies would never allow for the sharing of our derivation data with external research groups, (so much for open research). I think that for now, my only option will be to bodge superassignment to the global environment using random names, (so as not to overwrite anything the user has there), or to attempt to embed any required objects within the `coxph` model object prior to the `pseudo()` function call. I'm not sure the latter will work, but I'll give it a go.

Thank you for your help.

**Comment by Feakster** [comment]
Should I close this one?

**Comment by therneau** [comment]
The following worked for me:
  ....
  if (missing(newdata)) {
      temp <- data.frame(Y = object[['y']])
      kmfit <- survfit(Y ~ 1, data=newdata)
     }

**Comment by therneau** [comment]
Typo in the prior:  use data=temp in that last line.   (Or "newdata" like you did).  Sorry.
