### ISSUE TITLE
Use of `Surv()` in `coxph()` formula is problematic

### ISSUE THREAD

**Issue by dmurdoch** [therneau/survival#199]
This SO posting:  https://stackoverflow.com/q/72509288/2554330 tried to write a function to use in a `coxph()` formula to produce a `Surv()` object.  A simpler version of their code is as follows:

``` r
Surv2 <- function(AVAL = data$AVAL, 
                  CNSR = data$CNSR,
                  data = visR::adtte) {
  survival::Surv(time = AVAL, event = 1 - CNSR)
}
survival::coxph(Surv2() ~ SEX, data = visR::adtte)
#> Error in x[[2]]: subscript out of bounds
```

On the other hand, this works fine:

``` r
survival::coxph(Surv2(AVAL, CNSR) ~ SEX, data = visR::adtte)
#> Call:
#> survival::coxph(formula = Surv2(AVAL, CNSR) ~ SEX, data = visR::adtte)
#> 
#>        coef exp(coef) se(coef)     z     p
#> SEXM 0.3147    1.3699   0.1626 1.935 0.053
#> 
#> Likelihood ratio test=3.71  on 1 df, p=0.05412
#> n= 254, number of events= 152
```

The problem is that the  `survival:::terms.inner` function doesn't evaluate functions in the formula in the normal way, it
handles `Surv()` specially.   (Another way to fix the example is to name the function `Surv` instead of `Surv2`).  It would be less surprising and confusing if it split up the terms in the formula according to formula logic, then evaluated them in the right environment (i.e. `data`, followed by the environment of the formula), before deciding what to do based on the value, rather than relying on the way it was written.

**Comment by therneau** [comment]
Duncan,
There is a bug, but you have completely missed the point of the terms.inner function.  It is intended to be a limited analog of all.vars(), per the comments just above it.  It's job is not to evaluate anything, but to walk the parse tree while looking for certain text patterns.   If the string "Surv" is not seen, then it should act (mostly) like all.vars.  The problem is that I overlooked the case of a function with no arguments.   This is really easy to verify:
> all.vars( ~xyz())
 character(0)

> terms.inner(~xyz() )
  Error in x[[2]]: subscript out of bounds

It was also easy to fix: the updated version has one more line for my overlooked case:

terms.inner <- function(x) {
    if (inherits(x, "formula")) {
        if (length(x) ==3) c(terms.inner(x[[2]]), terms.inner(x[[3]]))
        else terms.inner(x[[2]])
    }
    else if (inherits(x, "call") && 
             (x[[1]] != as.name("$") && x[[1]] != as.name("["))) {
        if (x[[1]] == '+' || x[[1]]== '*' || x[[1]] == '-' || x[[1]] ==':') {
            # terms in a model equation, unary minus only has one argument
            if (length(x)==3) c(terms.inner(x[[2]]), terms.inner(x[[3]]))
            else terms.inner(x[[2]])
        }
        else if (x[[1]] == as.name("Surv"))
                 unlist(lapply(x[-1], terms.inner))
        else if (length(x) ==2) terms.inner(x[[2]])
        else character(0)
    }
    else(deparse(x))
}

For those who want to bastardize the language by adding modifiers everywhere, I have little sympathy.   A lot of formula processing depends on pattern recognition, not function evaluation.   Compare the following 2 results for example:

 fit1 <- glm( status ~ x + offset(log(time)), poisson, data= survival::aml)
 fit2 <- glm(status ~ x + stats::offset(log(time)), poisson, data= survival::aml)

The first is a sensible model, the second a mess.   I've had to respond to accusations that survival is "broken"  when same was done to a status() or cluster() term in the formula, i.e., things recognized as patterns by the specials argument to  terms.

**Comment by dmurdoch** [comment]
Yes, I didn't realize what it was doing.  Thanks for the fix!
