### ISSUE TITLE
  "number of variables != number of variable names" when predicting conditional logistical regression on a formula with minuses

### ISSUE THREAD

**Issue by jfsmenezes** [therneau/survival#208]
Hello,

I have come across a potential small bug. Whenever a `clogit()` is used with a formula that contains minuses, its runs correctly, but using `predict()` after will yield an error of type

```
Error in model.frame.default(data = newdata, formula = ~x, na.action = function (object, 
 :
  number of variables != number of variable names
```

_However, this kind of error only happens when the prediction is based on sample (`reference="sample"`)_

Here's a simple reproducible example:

```{r}
library(survival)

data = data.frame(
         y = sample(0:1,replace=T),   # dependent variable
         x = rep(letters[1:2],5),           # wanted independent variable
         z = rep(letters[1:3],4)[1:10],  #unwanted independent variable
         st = rep(letters[3:4],each=5) # strata
)

mod = clogit(y~x+z-z+strata(st),data=data) # does not converge, but error also happens with models that do.
mod2 = glm(y~x+z-z+st,data=data)             # an similar unconditional model

newdata= data.frame(x = sample(letters[1:2],10,replace=T),
                    z = sample(letters[1:3],10,replace=T), # for both models z must exist in newdata even if does not influence predicted values.
                    st= sample(letters[3:4],each=10))


predict(mod,newdata=newdata,reference="sample") # Error
predict(mod,newdata=newdata)                                 # Works perfectly
predict(mod2,newdata=newdata)                               # Works perfectly
```

Example run in a new instance of R 4.1.0 with  survival_3.2-13. No other packages loaded.

All this issue can be avoided by not using "-" in the formulas, so this potential bug is not critical. But minuses are specially useful in long models since it allow for very synthetic formulas, like `y~(.)^2-z`.  

I tried my best to find out how to fix it, but I can't figure out why it happens. the predict function seems to work until   `mf2 <- eval(tcall, parent.frame())`. Weirdly enough running this eval gives the error, but simply copying the content of `tcall` and pasting it on the console works like a charm.

**Comment by therneau** [comment]
You found a new failure in [.terms.   I've replaced the instance in predict.coxph with my internal drop.special function (as had been done in several other places in the code base), and have added a test for drop.specials to the tests directory.   One day we may get this issue fixed in base R.

 In several places the coxph functions use Terms[ - attr(Terms, "specials")$strata].   Strata needs to be in the model formula, in order to properly deal with missings and/or   covariate * strata interactions.  But it doesn't belong in the final X matrix, so you have to pull it out of the terms object before calling model.matrix.   There are a few special cases that mess up [.terms: an offset()  in the middle of a formula, or the construct  +x -x that you show are two of them.   They arise rarely, but survival has been around long enough for every corner case to arise.  The survival package, however, might be one of the only ones in R that uses that feature to drop things from the formula.   See the new tests/dropspecial.R function to see them all (all the ones I currently know of).
