### ISSUE TITLE
coxph function tie=exact

### ISSUE THREAD

**Issue by akarito** [therneau/survival#223]
why doesn't the coxph function provide the "tie=exact" option that calculated the average partial likelihood method in sas?

**Comment by therneau** [comment]
The exact partial likelihood, exact marginal likelihood,  Breslow and Efron approximations have all been suggested for the Cox model.   SAS labels the first two as "discrete" and  "exact",  I refer to the first as 'exact', and never implemented the second, which is due to Prentice I believe.   These labels are just labels, neither is more right or wrong than the other.

The reason that I've never implemented the exact marginal is that there is no reason to.  The survival package's development has been entirely driven by real data sets, and I have never seen an example or argument that showed any practical benefit to the marginal value.    There are rare cases, and they are rare, where the exact partial can be argued for.  In practice, though, I don't think I have never found a data set where exact partial and Efron differed enough to matter (i.e., differ by more than 1/4 std error).   

Why do you want the Prentice version?  I would be curious to finally see a practical reason for it.
