### ISSUE TITLE
NAs produced by integer overflow in very large coxph

### ISSUE THREAD

**Issue by bardwnb** [therneau/survival#54]
I'm trying to run a coxph on a large dataset, and it crashes with the following error:

```
Error in double(n * nvar) : vector size cannot be NA
Calls: coxph -> residuals.coxph -> double
In addition: Warning message:
In n * nvar : NAs produced by integer overflow
Execution halted
```

The model matrix has 48 columns and approximately 60 million rows.  I'm using weights and a cluster() term.  Another version of the same model on the same data but with 31 columns runs without error.  Similarly, when I was testing my code on a 10% sample of the data, the model with 48 columns, as well as another with over 100 columns, ran without error.

The error seems to be thrown in the call to either Ccoxscore or Cagscore between lines 104 and 129 in residuals.coxph.S, although I think the real problem must occur elsewhere.  The inputs for the offending line (`resid= double(n*nvar)`) are `n`, which is assigned `n <- length(object$residuals)` on line 16, and then `nvar` is assigned on line 49 as `nvar <- ncol(x)`.  

It doesn't seem like either one should be the problem--if I read the code correctly, `x` should have the same dimension as the model matrix, so `nvars` should be small, and `length()` should be able to handle a vector that exceeds the integer limit of 2^31-1.  So, I suspect that the problem is in creating the residuals back in coxph.fit, but I'm not sure how to proceed beyond that--any suggestions appreciated if there is a workaround here.

**Comment by therneau** [comment]
I much prefer an email conversation on things like this.  I push a copy of my local repository up to github  but log into it rarely.  
First of all, I am not going to implement your simple pull request absent a test case that proves it works.  The code is calling a C routine.  Have you looked at that routine to verify that it can handle a long vector?  Because if it uses integers as indices (it does) you have changed a simple error message to a potential memory corruption and core dump.   Depending on exactly how that routine does indexing the change may be okay and maybe not.    Since survival is used by so many, formal testing is something I take very seriously.
Because of the large number of things in my queue such testing isn't likely to happen any time soon.  As a statistician I have to ask why I need to prioritize this particular request since sampling is such a obvious answer.

**Comment by bardwnb** [comment]
I sense that through my ignorance I have committed a breach of github etiquette here.  My apologies--I will shoot you an e-mail.

**Comment by therneau** [comment]
No breach of etiquette, it is just that I only rarely log in here.  
Further research into the question leads to the conclusion that it's going to be serious work to fix, but I need to do it.  R now allows for matrices whose number of rows and number of columns are <2^31, but the total matrix has more than 2^31 elements; it did not allow the last when most of the survival routines were written, and the underlying C code uses integer subscripts throughout.  For a large matrix like this the coxph routine works fine but residuals.coxph fails, both the result of pure senendipity.  I need to do a full code review of all 43 C routines in the package

**Comment by therneau** [comment]
Further notes:  this conversation led to a more careful code review.  It turns out that entirely by accident,  due to a particular way I have traditionally handled matrix indexing, most of the C code for the survival package can handle large matrices.  That is, matrices where nrow and ncol are <  .Machine$integer.max, but the total matrix size could be larger.   Most places but not all.   My first reaction to bardwb's comments had actually been "how did it ever get THAT far?"  since I never planned for large matrices.  (Remember that the first iteration of coxph was in 1986, when memory objects this big were inconceivable. )
In any case, I will be doing a lot of code review in the next year wrt extending coxph to multi-state models.  I think that I should be able to make large matrices work throughout, and will be working to build that in.  It is actually not too hard, e.g. things like using allocMatrix instead of allocVector, but not trivial either.

**Comment by therneau** [comment]
The residuals routine has been converted to use .Call instead of .C, with corresponding changes to the underlying C code, it now used allocMatrix to create the result.   This should both the number or rows and the number of columns to be any value < the max integer.
