### ISSUE TITLE
Tidy evaluation in survfit

### ISSUE THREAD

**Issue by md0u80c9** [therneau/survival#57]
Hi,

Thankyou so much for your survival package.

I'm currently using it on a Shiny dashboard, where I want to vary the variable used to divide the cohorts. I have a line of code as follows (los_data() is a reactive function within my shiny app returning the data frame in case you're wondering):

`    fit <- survfit(Surv(LOS, event) ~ place_of_residence, data = los_data())

I wondered whether the package supports tidy evaluation (and whether I'm just not using it properly).

What I'm hoping can be done is along the lines of:

```
chart_series_value <- "place_of_residence"
enquo(chart_series_value)
fit <- survfit(Surv(LOS, event) ~ !!chart_series_value, data = los_data())

```

Is that possible and I've just done it wrong, or is it not supported within survival so far? If not, would it be possible to consider it as a feature?

**Comment by therneau** [comment]
I think that non-standard evaluation is a very bad idea, one that appears in a few spots in R proper.  When it works it is cute and simple to write, but having code that doesn't play by the rules eventually leads to a tar pit.   The NSE aspect of formulas has caused me a tremendous amout of hair pulling wrt the survival package in the last several years, almost enough to make me throw in the towel (like lm did) and always save the full data set as part of each fit object, which is not a good idea when data sets are huge. 

The tidyverse has decided to pursue the NSE idea to the extreme, and is a primary reason I ignore it; at least as far as the survival package.   There are now 500+ dependencies on survival, and I have to be very careful and very standard to avoid falling into a black hole of support. 

I passed the comment along to a colleague who knows the area better.  His comment:  "Yep.  Basically, he’s trying to use non-standard evaluation in a formula.  Don’t listen to him—no other modeling function supports it, because formulas don’t play well with NSE."     This sounds like way more work and trouble than I want to take on.
