### ISSUE TITLE
LogLik log and unLogged Response

### ISSUE THREAD

**Issue by ghost** [therneau/survival#61]
Dear,

I wish to calculate the likelihood of the model based on the actual observations instead of log(y) for Weibull and lognormal to compare my outputs with SAS proc lifereg.
How would this be accomplished?

**Comment by therneau** [comment]
Consider the following two fits
   fit1 <- survreg(Surv(time, status) ~ age + sex, data=lung, dist="lognormal")
   fit2 <- survreg(Surv(log(time), status) ~ age + sex, data=lung, dist="gaussian")

These two fits give exactly the same coefficients and standard errors, but the log-likelihoods differ by the factor ( Jacobian for log-normal vs Gaussian), i.e. the term you always have for change of variable in an integral.   This doesn't change likelihood ratio tests since, for any given data set, the factor is a constant.

The SAS lifereg procedure gets this wrong, however.   You can't have all three of "use untransformed y", "product the correct loglik", and "match SAS".
