### ISSUE TITLE
Handling of frailties in anova.coxph 

### ISSUE THREAD

**Issue by tobiasmuetze** [therneau/survival#74]
The `anova` method for coxph objects shows some unexpected behavior as the code below shows. In my opinion, the issue is that the `anova.coxph` method treats the frailty term as a fixed factor. 

```R
rm(list = ls())
library(survival)

# Define three models which are used to illustrate the issue
model1 <- coxph(Surv(time, status) ~ age + frailty.gamma(inst), lung)
model2 <- coxph(Surv(time, status) ~ frailty.gamma(inst) + age, lung)
model3 <- coxph(Surv(time, status) ~ frailty.gamma(inst), lung)

# Run anova-function on all three models
anova(model1)
anova(model2)
anova(model3)
```

In models 1 and 2, the degrees of freedom for the frist variable are one even though the variable that is added to the model first changes. In model 2, the frailty (which is added first) has one degree of freedom while in model 3, where the frailty is also added first, it has 7e-05 degree of freedom.

By the way, the `coxme` package does not test the frailty term which is in my opinion the more appropriate approach.

**Comment by therneau** [comment]
The anova command should be updated to simply say "anova not available for frailty models".   The problem is that frailty terms are mutable -- the random effects variance changes when a fixed effect is added or removed, which changes df, which essentially means the models are not nested.    You can get around this by using the integrated partial likelihood, which coxme is able to do, but coxph does not.

**Comment by therneau** [comment]
The anova.coxph.penal command has been updated to reject frailty terms.
