### ISSUE TITLE
Unexpected risk table with stratified start-stop type models

### ISSUE THREAD

**Issue by sven-stodtmann** [therneau/survival#81]
Example:
```{r} 
library(survival)
summary(
  survfit(
    coxph(Surv(start,stop,event)~1+strata(status)+cluster(id),
          data.frame(
            id=c(1,1,1,2,2,2,3,3,3,3),
            start=c(0,1,2,0,1,2,0,1,2,3),
            stop=c(1,2,3,1,2,3,1,2,3,4),
            event=c(0,0,1,0,0,0,0,0,0,0),
            status=factor(c(1,1,2,1,2,1,1,2,1,2))
          )
    )
  ),
  times=c(0,1,2,3,4)
)
```
results in
```
Call: survfit(formula = coxph(Surv(start, stop, event) ~ 1 + strata(status) + 
    cluster(id), data.frame(id = c(1, 1, 1, 2, 2, 2, 3, 3, 3, 
    3), start = c(0, 1, 2, 0, 1, 2, 0, 1, 2, 3), stop = c(1, 
    2, 3, 1, 2, 3, 1, 2, 3, 4), event = c(0, 0, 1, 0, 0, 0, 0, 
    0, 0, 0), status = factor(c(1, 1, 2, 1, 2, 1, 1, 2, 1, 2)))))

                1 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    0      3       0        1       0            1            1
    1      3       0        1       0            1            1
    2      1       0        1       0            1            1
    3      2       0        1       0            1            1

                2 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    0      2       0    1.000   0.000       1.0000            1
    1      2       0    1.000   0.000       1.0000            1
    2      2       0    1.000   0.000       1.0000            1
    3      1       1    0.368   0.368       0.0518            1
    4      1       0    0.368   0.368       0.0518            1
```

I would expect that n.risk in the '2' stratum starts at 0.

In particular this also brings the total #at risk across the strata to 5, I would expect that the total number at risk at each point within the strata adds up to the total number at risk.

for better readability, this is the dataset
```
   id start stop event status
1   1     0    1     0      1
2   1     1    2     0      1
3   1     2    3     1      2
4   2     0    1     0      1
5   2     1    2     0      2
6   2     2    3     0      1
7   3     0    1     0      1
8   3     1    2     0      2
9   3     2    3     0      1
10  3     3    4     0      2
```

**Comment by therneau** [comment]
Let me break the example out into parts, and change the data a little bit.
data2 <- data.frame(id=c(1,1,1,2,2,2,3,3,3,3),
                     start=c( 1, 5, 10, 2, 5, 10, 3, 6, 11, 15),
                    stop= c( 6, 11, 16, 6,11,16, 6,11,16, 20), 
                    event=c(0,0,1,0,0,0,0,0,0,0),
                    group=factor(c(1,1,2,1,2,1,1,2,1,2)))

fit2 <- survfit(Surv(start, stop, event) ~ group, id=id, data=tdata)

names(fit2)
f [1] "n"         "time"      "n.risk"    "n.event"   "n.censor"  "surv"     
 [7] "std.err"   "cumhaz"    "std.chaz"  "strata"    "type"      "logse"    
[13] "conf.int"  "conf.type" "lower"     "upper"     "call"     

> fit2$time
[1]  6 11 16 11 16 20

You'll notice 2 things: the time element only includes the ending times, and there is no "n.add" component.    That means that the result of survfit, as constructed, does not contain the information about additions to the number at risk in between the event times.   Formally, the number at risk in the above data is changes multiple times between 0 and first event at 6, but that information is not saved.  The print routine makes assumptions rather than print an NA.

I had the stubs to add this feature in the code at one time, but never had a use case for it -- i.e. an actual data set where I needed those numbers.   So it has never been done.   The fact that it will break much of my test suite, along with the tests for at least 20 other packages  seriously dampens my enthusiasm for changing it.  (In a recent update to the survival suite,  I added a time 0 point to the results, and quickly found out how much would break.  That change was quickly reverted!)
