### ISSUE TITLE
coxph gives incorrect result when cluster is used with explicit namespace definition

### ISSUE THREAD

**Issue by stefanoborini** [therneau/survival#86]
The following give two different results:

```
survival::coxph(survival::Surv(time,event)~arm+survival::cluster(id),weights=wgt,data=test.dat)
```

Gives:
```
Call:
survival::coxph(formula = survival::Surv(time, event) ~ arm + 
    survival::cluster(id), data = test.dat, weights = wgt)

                        coef exp(coef) se(coef)     z    p
arm                    0.246     1.279    0.663  0.37 0.71
survival::cluster(id) -0.167     0.846    0.128 -1.30 0.19
```

Using:

```
cluster = survival::cluster
survival::coxph(survival::Surv(time,event)~arm+cluster(id),weights=wgt,data=test.dat)
```

Gives:

```
survival::coxph(formula = survival::Surv(time, event) ~ arm + 
    cluster(id), data = test.dat, weights = wgt)

       coef exp(coef) se(coef) robust se     z    p
arm -0.0278    0.9726   0.6330    0.5161 -0.05 0.96

Likelihood ratio test=0  on 1 df, p=1
n= 10, number of events= 10 
```

The namespace should be stripped away automatically at the very least.

**Comment by therneau** [comment]
You have created an invalid formula.   The best response, perhaps, is for me to add an explicit check and error message.   Your assumption about how it "should" work is incorrect.   Formulas parse expressions using certain rules, they do not evaluate functions.   It's low on the priority list though.

 And on a side note, why are people so interested in self-flagellation (sprinkling  :: everywhere)?  It seems to all the rage in certain circles.

**Comment by stefanoborini** [comment]
@therneau because it's recommended practice in the [Google R style guide](https://google.github.io/styleguide/Rguide.html#qualifying-namespaces) and it guarantees that you are actually referring to the proper entity from the proper namespace, rather than whatever happens to be in the global namespace.

**Comment by therneau** [comment]
Google can publish any internal style guides they want, that does not make them a good idea elsewhere.  

Carrying the suggestion to the extreme, as you did, leads to incorrect code in this case.   Plus it is completely unnecessary:  arguments within the coxph call will be evaluated in the survival namespace.   The Surv and cluster portions will not be confused with other functions of the same name found somewhere else.    The google guide needs an update.

In your second example, for instance,  the cluster() function you defined will never be referenced.

**Comment by stefanoborini** [comment]
> arguments within the coxph call will be evaluated in the survival namespace.

arguments in the coxph call. Not calls that are not part of that call. Our external code is massive and we face potential namespace clashes all the time.

> The Surv and cluster portions will not be confused with other functions of the same name found somewhere else. The google guide needs an update.

The google guide is relative to code outside survival code, not to code inside it. You are free to operate as you wish, but for us, that we have to ensure a reliable environment and proper coding documentation, it's important. If I see a function call survival() I have no idea if whoever wrote this code is referring to survival survival or his survival.

**Comment by therneau** [comment]
Use survival::coxph instead of coxph, I have no objection; your comments certainly apply to the outer function name.   But within the coxph call your addition of survival:: to the Surv and cluster portions of the formula is redundant, unnecessary, and dangerous.     I am not going to add non-standard evaluation methods to coxph formula processing to fix an "error" that is not my error.  (The model.frame() and terms() functions are base R, and I'd have to create my own variants.)   Every function that uses the specials argument to terms(), not just survival, will be potentially clobbered by your rule.  Specials are "special" ("odd" would also be fair)  and you can't think of them as a  function call; they are certain distinct words that get identified.   I don't have a glossary of all the functions that use the specials argument to terms,  but it goes back to at least 1992 so I would guess that there are quite a few.

My argument for an update is that a sentence of warning should be added about the danger of blind substitution of :: terms within a formula.   Like English spelling, one must be cognisant of exceptions.  I certainly won't argue for a global change in your policy.  

"Your package fails because Google's policy breaks a feature in base R, fix your package" won't fly though,  Nevertheless, you won't be the last to make this particular mistake.  I'll think about whether there is a way to create an appropriate error message without causing other problems.  There are over 650 other packages that depend on survival; I can never make a fundamental change lightly.
